
service: generateotp

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.handler #lambda
    timeout: 900 #lambda
    memorySize: 128 #lambda
